# Introducción a Pandas — Ejercicios resueltos

## Preparación
Importamos las bibliotecas y reconstruimos el DataFrame original. Las respuestas de limpieza se calculan por separado para conservar los datos originales entre ejercicios.

In [1]:
import pandas as pd
import numpy as np

people_data = {
    'name': ['María', 'Daniel', 'Marisa', 'David', 'Sabrina'],
    'age': [16, 7, 29, None, 33],
    'city': ['Madrid', 'Madrid', 'Málaga', 'Málaga', 'Valladolid'],
    'height': [None, 1.20, 1.60, 2.01, 1.83]
}
people_df = pd.DataFrame(people_data)
print('El DataFrame original contiene 5 personas:')
display(people_df)

El DataFrame original contiene 5 personas:

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

Toma el dataframe original y guárdalo como un CSV

**Procedimiento:** Se guarda la tabla en un archivo CSV sin añadir el índice como columna.

In [2]:
csv_path = 'data.csv'
people_df.to_csv(csv_path, index=False)
print(f'El DataFrame se ha guardado localmente en {csv_path}.')

El DataFrame se ha guardado localmente en data.csv.

Ahora lee el archivo CSV

**Procedimiento:** Leemos el CSV generado y mostramos el contenido recuperado.

In [3]:
people_df = pd.read_csv(csv_path)
print('El contenido del archivo CSV es:')
display(people_df)

El contenido del archivo CSV es:

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

Muestra los 3 primeros registros del DataFrame.

**Procedimiento:** Usamos head(3) para seleccionar las tres primeras filas.

In [4]:
first_three_people = people_df.head(3)
print('Los 3 primeros registros son:')
display(first_three_people)

Los 3 primeros registros son:

     name   age    city  height
0   María  16.0  Madrid     NaN
1  Daniel   7.0  Madrid     1.2
2  Marisa  29.0  Málaga     1.6

Muestra los 4 últimos registros del DataFrame.

**Procedimiento:** Usamos tail(4) para seleccionar las cuatro últimas filas.

In [5]:
last_four_people = people_df.tail(4)
print('Los 4 últimos registros son:')
display(last_four_people)

Los 4 últimos registros son:

      name   age        city  height
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

Dime cuantos datos tiene el DataFrame (💡 es lo mismo que calcular el número de filas). ¿en `numpy` vimos 2 formas de calcular este dato, recuerdas?

**Procedimiento:** Calculamos las filas con len() y con la primera dimensión de shape. No usamos size, que contaría todas las celdas.

In [6]:
row_count = len(people_df)
row_count_from_shape = people_df.shape[0]
print(f'El DataFrame tiene {row_count} filas según len() y {row_count_from_shape} según shape[0].')

El DataFrame tiene 5 filas según len() y 5 según shape[0].

Muéstrame las estadísticas básicas del DataFrame.

**Procedimiento:** describe() resume las columnas numéricas e ignora los valores nulos al calcular las estadísticas.

In [7]:
summary_statistics = people_df.describe()
print('Las estadísticas básicas de las columnas numéricas son:')
display(summary_statistics)

Las estadísticas básicas de las columnas numéricas son:

             age    height
count   4.000000  4.000000
mean   21.250000  1.660000
std    11.954776  0.349571
min     7.000000  1.200000
25%    13.750000  1.500000
50%    22.500000  1.715000
75%    30.000000  1.875000
max    33.000000  2.010000

Obtén los datos de la columna 'name' ¿Cual es el tipo de dato de esta columna?

**Procedimiento:** Seleccionamos name. Distinguimos la estructura de la columna (Series) del tipo de sus datos (texto).

In [8]:
names = people_df['name']
print('Los nombres de las personas son:')
display(names)
print(f'La columna es una {type(names).__name__} y su dtype es {names.dtype}; contiene texto.')

Los nombres de las personas son:

0      María
1     Daniel
2     Marisa
3      David
4    Sabrina
Name: name, dtype: object

La columna es una Series y su dtype es object; contiene texto.

🌶️ Recuera que una Serie se puede tratar como un array de numpy, por tanto, obtén los datos de la columna "age" y calcula la media. ¿Coincide con el resultado que arroja pandas en la celda superior? (💡 en `numpy` la media se calcula usando `np.mean`)

**Procedimiento:** Convertimos las edades en un array y excluimos los valores nulos antes de usar np.mean(). Así comparamos la media de las edades conocidas con Pandas, que ignora los nulos por defecto.

In [9]:
ages = people_df['age']
valid_ages = ages.dropna().to_numpy()
numpy_mean_age = np.mean(valid_ages)
pandas_mean_age = ages.mean()
print(f'La edad media con NumPy es de {numpy_mean_age:.2f} años.')
print(f'La edad media con Pandas es de {pandas_mean_age:.2f} años.')
print(f'¿Coinciden los resultados? {"Sí" if np.isclose(numpy_mean_age, pandas_mean_age) else "No"}.')

La edad media con NumPy es de 21.25 años.
La edad media con Pandas es de 21.25 años.
¿Coinciden los resultados? Sí.

Ahora calcula la edad máxima y mínima de la columna "age".

**Procedimiento:** Calculamos el máximo y el mínimo de las edades conocidas.

In [10]:
maximum_age = people_df['age'].max()
minimum_age = people_df['age'].min()
print(f'La edad máxima es de {maximum_age:.0f} años y la mínima es de {minimum_age:.0f} años.')

La edad máxima es de 33 años y la mínima es de 7 años.

🌶️ Una vez obtenida la edad mínima, ¿Cual es el nombre de dicha persona?

**Procedimiento:** idxmin() devuelve el índice de la edad mínima. Usamos loc para consultar el nombre de esa fila.

In [11]:
youngest_person_index = people_df['age'].idxmin()
youngest_person_name = people_df.loc[youngest_person_index, 'name']
print(f'La persona de menor edad se llama {youngest_person_name}.')

La persona de menor edad se llama Daniel.

Filtra el DataFrame: muestra las filas donde la edad sea mayor a 25.

**Procedimiento:** Aplicamos una condición para seleccionar edades superiores a 25.

In [12]:
older_people = people_df[people_df['age'] > 25]
print('Las personas mayores de 25 años son:')
display(older_people)

Las personas mayores de 25 años son:

      name   age        city  height
2   Marisa  29.0      Málaga    1.60
4  Sabrina  33.0  Valladolid    1.83

Filtra el DataFrame: muestra las filas donde la gente sea de 'Málaga'. (💡 utiliza el operador `==`)

**Procedimiento:** Comparamos la ciudad con Málaga mediante ==.

In [13]:
malaga_people = people_df[people_df['city'] == 'Málaga']
print('Las personas de Málaga son:')
display(malaga_people)

Las personas de Málaga son:

     name   age    city  height
2  Marisa  29.0  Málaga    1.60
3   David   NaN  Málaga    2.01

🌶️ Filtra el Dataframe: filas donde la gente sea de 'Málaga' y mayor de 25. (💡 para sumar dos condiciones se utiliza el operador `and` que se representa en python con `&`, i.e.: 

```python
compose_condition = condition1 & condition2
```

**Procedimiento:** Combinamos las dos condiciones con & y ponemos cada condición entre paréntesis. La edad desconocida de David no cumple el filtro.

In [14]:
malaga_and_over_25 = (people_df['city'] == 'Málaga') & (people_df['age'] > 25)
older_malaga_people = people_df[malaga_and_over_25]
print('Las personas de Málaga mayores de 25 años son:')
display(older_malaga_people)

Las personas de Málaga mayores de 25 años son:

     name   age    city  height
2  Marisa  29.0  Málaga     1.6

Obtén la máscara de los valores que son nulos en el DataFrame.

**Procedimiento:** isnull() devuelve True donde hay un dato ausente.

In [15]:
missing_values_mask = people_df.isnull()
print('La máscara indica con True los valores nulos:')
display(missing_values_mask)

La máscara indica con True los valores nulos:

    name    age   city  height
0  False  False  False    True
1  False  False  False   False
2  False  False  False   False
3  False   True  False   False
4  False  False  False   False

Ahora obtén la máscara de los valores que NO son nulos en el DataFrame. (💡 busca en la documentación de pandas, o en google, cómo hacerlo)

**Procedimiento:** notnull() devuelve True donde hay un dato presente. También se puede usar notna().

In [16]:
non_missing_values_mask = people_df.notnull()
print('La máscara indica con True los valores que no son nulos:')
display(non_missing_values_mask)

La máscara indica con True los valores que no son nulos:

   name    age  city  height
0  True   True  True   False
1  True   True  True    True
2  True   True  True    True
3  True  False  True    True
4  True   True  True    True

Elimina los valores nulos del DataFrame.

**Procedimiento:** dropna() elimina las filas que contienen algún nulo. Guardamos el resultado aparte para mantener el DataFrame original.

In [17]:
complete_people_df = people_df.dropna()
print(f'Tras eliminar las filas con valores nulos, quedan {len(complete_people_df)} personas:')
display(complete_people_df)

Tras eliminar las filas con valores nulos, quedan 3 personas:

      name   age        city  height
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
4  Sabrina  33.0  Valladolid    1.83

Rellena todos los valores nulos con 1.

**Procedimiento:** Rellenamos los valores ausentes con 1 y guardamos el resultado en otra variable.

In [18]:
filled_people_df = people_df.fillna(1)
print('El DataFrame con todos los valores nulos sustituidos por 1 es:')
display(filled_people_df)

El DataFrame con todos los valores nulos sustituidos por 1 es:

      name   age        city  height
0    María  16.0      Madrid    1.00
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   1.0      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

Ahora rellena sólo los valores nulos de la columna 'age' con 10.

**Procedimiento:** fillna() con un diccionario permite rellenar únicamente la columna age.

In [19]:
age_filled_people_df = people_df.fillna({'age': 10})
print('El DataFrame con la edad desconocida sustituida por 10 es:')
display(age_filled_people_df)

El DataFrame con la edad desconocida sustituida por 10 es:

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David  10.0      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

🌶️ Ahora rellena los valores nulos de la columna 'height' con la media de dicha columna

**Procedimiento:** Calculamos la media de las alturas conocidas y rellenamos solo los valores ausentes de height.

In [20]:
mean_height = people_df['height'].mean()
height_filled_people_df = people_df.fillna({'height': mean_height})
print(f'La altura media es {mean_height:.2f} m; sustituimos por ella la altura desconocida:')
display(height_filled_people_df)

La altura media es 1.66 m; sustituimos por ella la altura desconocida:

      name   age        city  height
0    María  16.0      Madrid    1.66
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

## BONUS: Explora los datos del dataset de Titanic

El dataset se lee directamente desde su URL. Contiene información sobre los pasajeros, como edad, clase y supervivencia.

In [21]:
titanic_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic_df = pd.read_csv(titanic_url)
print(f'El dataset contiene {len(titanic_df)} pasajeros. Sus primeros 5 registros son:')
display(titanic_df.head(5))

El dataset contiene 891 pasajeros. Sus primeros 5 registros son:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**¿Qué porcentaje de pasajeros sobrevivió?**

**Procedimiento:** Survived vale 1 para supervivientes y 0 para el resto. Su media multiplicada por 100 proporciona el porcentaje.

In [22]:
survival_rate = titanic_df['Survived'].mean() * 100
print(f'La tasa de supervivencia es del {survival_rate:.2f}%.')

La tasa de supervivencia es del 38.38%.

**¿Cuál es la edad media de los pasajeros?**

**Procedimiento:** Calculamos la media de las edades conocidas; los valores ausentes se omiten.

In [23]:
mean_passenger_age = titanic_df['Age'].mean()
print(f'La edad media de los pasajeros con edad conocida es de {mean_passenger_age:.2f} años.')

La edad media de los pasajeros con edad conocida es de 29.70 años.

**¿Cuántos pasajeros había en cada clase?**

**Procedimiento:** Contamos los valores de Pclass y ordenamos por clase.

In [24]:
passengers_by_class = titanic_df['Pclass'].value_counts().sort_index()
for passenger_class, passenger_count in passengers_by_class.items():
    print(f'En la clase {passenger_class} había {passenger_count} pasajeros.')

En la clase 1 había 216 pasajeros.
En la clase 2 había 184 pasajeros.
En la clase 3 había 491 pasajeros.

**¿Cuál es la edad media de los pasajeros que sobrevivieron y de los que no?**

**Procedimiento:** Agrupamos por supervivencia y calculamos la media de las edades conocidas de cada grupo.

In [25]:
mean_age_by_survival = titanic_df.groupby('Survived')['Age'].mean()
print(f'La edad media de quienes sobrevivieron es de {mean_age_by_survival.loc[1]:.2f} años.')
print(f'La edad media de quienes no sobrevivieron es de {mean_age_by_survival.loc[0]:.2f} años.')

La edad media de quienes sobrevivieron es de 28.34 años.
La edad media de quienes no sobrevivieron es de 30.63 años.

**¿Cuál es la edad máxima de los pasajeros que sobrevivieron y de los que no?**

**Procedimiento:** Agrupamos por supervivencia y obtenemos la mayor edad conocida de cada grupo.

In [26]:
maximum_age_by_survival = titanic_df.groupby('Survived')['Age'].max()
print(f'La edad máxima de quienes sobrevivieron es de {maximum_age_by_survival.loc[1]:.0f} años.')
print(f'La edad máxima de quienes no sobrevivieron es de {maximum_age_by_survival.loc[0]:.0f} años.')

La edad máxima de quienes sobrevivieron es de 80 años.
La edad máxima de quienes no sobrevivieron es de 74 años.